enable-magisk-update = true

[YouTube]
build-mode = "both"
excluded-patches = "'Enable debugging'"
version = "auto"
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
